import { Box } from "@mui/material";
import "./about.scss";

const About = () => {
    return (
        <Box className="about">
            <Box
                component="section"
                className="about__section">
                <h3>Misión</h3>
                <img
                    src="/images/about/mision.png"
                    alt="Fotografía de la misión de la empresa" />
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, accusamus facilis laboriosam doloribus sapiente maiores possimus voluptatum aperiam beatae voluptatem quis ipsum quaerat quibusdam assumenda, minima eius fugiat voluptates praesentium ratione placeat. Dolorum placeat possimus dolore necessitatibus voluptas repudiandae asperiores sequi. Eos ut repellat consequuntur commodi omnis iure minima ipsam tempore cumque, dolor ratione placeat inventore enim qui aperiam nulla doloremque! Quae, molestiae ad. Exercitationem, odio esse quibusdam officia repudiandae dolor, repellat, dolore quas ab adipisci eaque culpa. Similique laudantium at, dignissimos repellat tempore labore natus obcaecati repudiandae. Eaque cupiditate magni ea, quia labore dignissimos praesentium dicta officia in nihil illum odit explicabo vitae illo atque alias molestias molestiae ipsam earum obcaecati delectus? Laudantium delectus sapiente at perspiciatis natus eum ab aspernatur repellat? Consectetur libero ut placeat harum, assumenda obcaecati id eaque quia. Quidem perspiciatis eaque amet suscipit vel, repellendus laudantium numquam doloremque saepe velit. Veritatis pariatur ipsum fugiat atque, blanditiis aliquid in quo laudantium quam quisquam beatae illum, consectetur alias incidunt explicabo doloribus placeat totam eos vero autem. Dolorum similique repudiandae quas optio voluptate expedita. Dolores necessitatibus ipsam quo. Quis in dolores alias. Nostrum facere iure officiis, ipsum quaerat harum aspernatur explicabo molestias impedit adipisci quidem distinctio neque minima rem necessitatibus non, dolore sapiente dolorum cum sed? Magni ducimus deserunt assumenda corporis atque. Omnis totam sunt reiciendis earum debitis, in exercitationem modi at! Officia, dolore id placeat aperiam fugit officiis eaque, quod iusto temporibus quis accusantium atque ad nesciunt cupiditate voluptatum natus. Consequuntur et numquam dolorem voluptas iure hic, culpa enim eaque nulla reprehenderit, repellendus tenetur, est perspiciatis placeat similique? Dolorum accusamus nihil quaerat molestiae quidem tenetur, error praesentium veritatis, expedita consequuntur alias impedit dignissimos maxime vel obcaecati ipsa optio temporibus distinctio iste? Quisquam dolorem nihil voluptatum modi perspiciatis illo optio commodi, asperiores cum molestias id corrupti odio qui.</p>
            </Box>
            <Box
                component="section"
                className="about__section about__section--vision">
                <h3>Visión</h3>
                <img
                    src="/images/about/vision.png"
                    alt="Fotografía de la visión de la empresa" />
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, accusamus facilis laboriosam doloribus sapiente maiores possimus voluptatum aperiam beatae voluptatem quis ipsum quaerat quibusdam assumenda, minima eius fugiat voluptates praesentium ratione placeat. Dolorum placeat possimus dolore necessitatibus voluptas repudiandae asperiores sequi. Eos ut repellat consequuntur commodi omnis iure minima ipsam tempore cumque, dolor ratione placeat inventore enim qui aperiam nulla doloremque! Quae, molestiae ad. Exercitationem, odio esse quibusdam officia repudiandae dolor, repellat, dolore quas ab adipisci eaque culpa. Similique laudantium at, dignissimos repellat tempore labore natus obcaecati repudiandae. Eaque cupiditate magni ea, quia labore dignissimos praesentium dicta officia in nihil illum odit explicabo vitae illo atque alias molestias molestiae ipsam earum obcaecati delectus? Laudantium delectus sapiente at perspiciatis natus eum ab aspernatur repellat? Consectetur libero ut placeat harum, assumenda obcaecati id eaque quia. Quidem perspiciatis eaque amet suscipit vel, repellendus laudantium numquam doloremque saepe velit. Veritatis pariatur ipsum fugiat atque, blanditiis aliquid in quo laudantium quam quisquam beatae illum, consectetur alias incidunt explicabo doloribus placeat totam eos vero autem. Dolorum similique repudiandae quas optio voluptate expedita. Dolores necessitatibus ipsam quo. Quis in dolores alias. Nostrum facere iure officiis, ipsum quaerat harum aspernatur explicabo molestias impedit adipisci quidem distinctio neque minima rem necessitatibus non, dolore sapiente dolorum cum sed? Magni ducimus deserunt assumenda corporis atque. Omnis totam sunt reiciendis earum debitis, in exercitationem modi at! Officia, dolore id placeat aperiam fugit officiis eaque, quod iusto temporibus quis accusantium atque ad nesciunt cupiditate voluptatum natus. Consequuntur et numquam dolorem voluptas iure hic, culpa enim eaque nulla reprehenderit, repellendus tenetur, est perspiciatis placeat similique? Dolorum accusamus nihil quaerat molestiae quidem tenetur, error praesentium veritatis, expedita consequuntur alias impedit dignissimos maxime vel obcaecati ipsa optio temporibus distinctio iste? Quisquam dolorem nihil voluptatum modi perspiciatis illo optio commodi, asperiores cum molestias id corrupti odio qui.</p>
            </Box>
            <Box
                component="section"
                className="about__section">
                <h3>Valores</h3>
                <img
                    src="/images/about/valores.png"
                    alt="Fotografía de los valores de la empresa" />
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quidem, accusamus facilis laboriosam doloribus sapiente maiores possimus voluptatum aperiam beatae voluptatem quis ipsum quaerat quibusdam assumenda, minima eius fugiat voluptates praesentium ratione placeat. Dolorum placeat possimus dolore necessitatibus voluptas repudiandae asperiores sequi. Eos ut repellat consequuntur commodi omnis iure minima ipsam tempore cumque, dolor ratione placeat inventore enim qui aperiam nulla doloremque! Quae, molestiae ad. Exercitationem, odio esse quibusdam officia repudiandae dolor, repellat, dolore quas ab adipisci eaque culpa. Similique laudantium at, dignissimos repellat tempore labore natus obcaecati repudiandae. Eaque cupiditate magni ea, quia labore dignissimos praesentium dicta officia in nihil illum odit explicabo vitae illo atque alias molestias molestiae ipsam earum obcaecati delectus? Laudantium delectus sapiente at perspiciatis natus eum ab aspernatur repellat? Consectetur libero ut placeat harum, assumenda obcaecati id eaque quia. Quidem perspiciatis eaque amet suscipit vel, repellendus laudantium numquam doloremque saepe velit. Veritatis pariatur ipsum fugiat atque, blanditiis aliquid in quo laudantium quam quisquam beatae illum, consectetur alias incidunt explicabo doloribus placeat totam eos vero autem. Dolorum similique repudiandae quas optio voluptate expedita. Dolores necessitatibus ipsam quo. Quis in dolores alias. Nostrum facere iure officiis, ipsum quaerat harum aspernatur explicabo molestias impedit adipisci quidem distinctio neque minima rem necessitatibus non, dolore sapiente dolorum cum sed? Magni ducimus deserunt assumenda corporis atque. Omnis totam sunt reiciendis earum debitis, in exercitationem modi at! Officia, dolore id placeat aperiam fugit officiis eaque, quod iusto temporibus quis accusantium atque ad nesciunt cupiditate voluptatum natus. Consequuntur et numquam dolorem voluptas iure hic, culpa enim eaque nulla reprehenderit, repellendus tenetur, est perspiciatis placeat similique? Dolorum accusamus nihil quaerat molestiae quidem tenetur, error praesentium veritatis, expedita consequuntur alias impedit dignissimos maxime vel obcaecati ipsa optio temporibus distinctio iste? Quisquam dolorem nihil voluptatum modi perspiciatis illo optio commodi, asperiores cum molestias id corrupti odio qui.</p>
            </Box>
        </Box>
    );
};

export default About;